// <auto-generated />
namespace AccionLaboral.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class first_mig_7_feb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(first_mig_7_feb));
        
        string IMigrationMetadata.Id
        {
            get { return "201502071736059_first_mig_7_feb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
